name: Run Tests
on: [push]
jobs:
  run-golang-tests:
    runs-on: ubuntu-20.04
    name: Run Golang Tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - run: go version
      - run: go test ./scripts/test_utils/...
