name: Validate Posts
on: [push]
jobs:
  validate-posts:
    runs-on: ubuntu-20.04
    name: Validate Posts
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - run: go version
      - run: go test ./scripts/posts_test.go
